### ISSUE TITLE
Settings?

### ISSUE THREAD

**Issue by marmalodak** [jamesturk/django-markupfield#34]
I'm somewhat unclear on where the settings belong.

Do the markup type choices belong in the model file of each model?  Or do they go into myapp/settings.py?   

Thanks for create this django extension, it looks like it might be exactly what I wished for.

**Comment by jamesturk** [comment]
Depending on your needs, MARKUP_FIELD_TYPES can be in your project's settings.py or passed in to each field individually if you need different fields to have different choices.

Let me know if that resolves it for you

**Comment by marmalodak** [comment]
Thank you, I think it does.  Pardon the newcomer questions, I have only limited experience with Django.

I pasted that snippet from your "Settings" section, and I'll run with that.

I plan to offer 'plain', 'markdown', and 'restructuredtext' - what is the renderer for plain?

**Comment by jamesturk** [comment]
try leaving it undefined, the default has those in it.

if you want to look at plain it is in the source, basically just urlifys and strips text using some built in Django helpers

**Comment by marmalodak** [comment]
That works nicely, thank you.  I just wanted to remove the HTML option since, as your how-to states, it is unsafe.
