### ISSUE TITLE
:linenos: param is not parsed??

### ISSUE THREAD

**Issue by s2krish** [jamesturk/django-markupfield#38]
Hi,

I have following code-block

    .. code-block:: HTML
       :linenos:

Then it is giving error like `Error in "code-block" directive: unknown option: "linenos".`

What is the issue? I am using markfield 1.4.0, and docutils 0.12. My setting is like:

    import markdown
    from docutils.core import publish_parts
    
    def render_rest(markup):
        parts = publish_parts(source=markup, writer_name="html4css1")
        return parts["fragment"]
    
    MARKUP_FIELD_TYPES = (
        ('markdown', markdown.markdown),
        ('ReST', render_rest),
    )

Thanks, and I select markup type ReST while saving.

**Comment by jamesturk** [comment]
I think this is an issue w/ docutils, I'm not sure linenos is an option it
accepts?

I'm not seeing it here:
http://docutils.sourceforge.net/docs/ref/rst/directives.html  but do you
have it working elsewhere?

**Comment by jamesturk** [comment]
let me know if this is still an issue for you, otherwise I'll close this in a few days, thanks!

**Comment by s2krish** [comment]
Thanks @jamesturk you are right the issue is with docutils. `http://sphinx-doc.org/` allow this. I realized that Sphinx it has custom directive. Yes, please close it.
