### ISSUE TITLE
Django Modelform not saving field (Django 1.9)

### ISSUE THREAD

**Issue by gbozee** [jamesturk/django-markupfield#39]
I just ran into an issue saving a markupfield from django admin. But the field isn't updated instead, it escapes the existing rendered value. Saving the field manually works but not when using django model forms.

**Comment by jamesturk** [comment]
Do you think it'd be possible to reproduce (either via a test or via a
stripped down version of your code that demonstrates the issue?)?

**Comment by gbozee** [comment]
Looks like the error I ran into has been fixed in the latest pip version. Sorry for any inconvenience
