### ISSUE TITLE
Markdown is stored as HTML in the database

### ISSUE THREAD

**Issue by bendavis78** [jamesturk/django-markupfield#45]
I have a field declared as: ` MarkupField(blank=True, markup_type='markdown')`. When I save this field in the database, it's converted to HTML. How do I make it store as markdown in the database?

**Comment by jamesturk** [comment]
MarkupField actually stores two fields in the db, a raw and a rendered
field.  The raw field is markdown, the rendered is HTML.  If you want only
markdown stored this project is probably not for you as you could get away
w/ just a TextField :)
