### ISSUE TITLE
indexing MarkupFields with wagtail & elasticsearch

### ISSUE THREAD

**Issue by alee** [jamesturk/django-markupfield#46]
We are running into issues when indexing a Django model with MarkupFields into Elasticsearch [using wagtail](http://docs.wagtail.io/en/v1.13/topics/search/indexing.html#example). The `Markup` object returned when accessing the field property can't be serialized to Elasticsearch. 

There's a few ways around this but I'd like to avoid having to create additional methods (e.g., `get_raw_foo`). I *think* the easiest way would be to add a `get_searchable_content` method to the `Markup` class that returns the raw source or to somehow make the MarkupField more open to extension.. I can't extend the MarkupField class directly since it gets replaced with the Markup class.

Thoughts? And thank you for contributing & maintaining this!

**Comment by jamesturk** [comment]
Hey- thanks for the comment & interest.  I'd be glad to see this fixed, but
don't have a ton of wagtail experience, but if you could provide something
that worked I'd be glad to accept it as it sounds pretty minimally invasive
