### ISSUE TITLE
ArrayField(MarkupField()) support

### ISSUE THREAD

**Issue by mlaugharn** [jamesturk/django-markupfield#58]
I think that ArrayFields of MarkupFields doesn't work

**Comment by jamesturk** [comment]
Given the way this is implemented and the way ArrayFields work as native fields in the DB, this isn’t really feasible as far as i can imagine.

**Comment by jamesturk** [comment]
Looked into this a bit more and I don't think this will be supported.  If something like this were needed I'd either implement the rendering myself & store two parallel arrays, or use something like a JSONField to mimic a composite field type.
